## 1. WAP to implement a Perceptron using numpy in Python.

### ->*Import numpy*

In [50]:
import numpy as np

### ->*Taking a data.csv file to implement preceptron*

In [51]:
import pandas as pd
data = pd.read_csv('data.csv')
data

    Pattern  Feature1  Feature2  Feature3  Class_Label
0         1         1      0.08      0.72            1
1         2         1      0.10      1.00            1
2         3         1      0.26      0.58            1
3         4         1      0.35      0.95            0
4         5         1      0.45      0.15            1
5         6         1      0.60      0.30            1
6         7         1      0.70      0.65            0
7         8         1      0.92      0.45            0
8         9         1      0.42      0.85            0
9        10         1      0.65      0.55            0
10       11         1      0.20      0.30            1
11       12         1      0.20      1.00            0
12       13         1      0.85      0.10            1

In [52]:
data = data.drop(columns='Feature1')
data = data.drop(columns='Feature2')
data = data.drop(columns='Pattern')
data

    Feature3  Class_Label
0       0.72            1
1       1.00            1
2       0.58            1
3       0.95            0
4       0.15            1
5       0.30            1
6       0.65            0
7       0.45            0
8       0.85            0
9       0.55            0
10      0.30            1
11      1.00            0
12      0.10            1

In [53]:
X = np.array(data.drop(columns="Class_Label"))
X.shape

(13, 1)

In [54]:
Y = np.array(data.drop(columns=["Feature2","Feature3"]))
Y.shape

KeyError: "['Feature2'] not found in axis"

    Activation Function g(x) = {1 if x >= 0,
                                0 if x < 0}

In [55]:
def activationFunction(x):
    return 1 if x >= 0 else 0

In [56]:
def netInputFunction(X, W):
    return np.dot(X, W)

In [57]:
def perceptronUpdateRule(X, W, Y):
    for i in range(len(X)):
        y = activationFunction(netInputFunction(X[i], W))
        W = W + (Y[i] - y) * X[i]
    return W

In [58]:
def approximation(X, W):
    return [activationFunction(netInputFunction(X[i], W)) for i in range(len(X))]

Training

In [59]:
def train(X, Y, W):
    for i in range(len(Y)):
        W[i] = perceptronUpdateRule(X, W[i], Y[i])
    return W

In [64]:
waights = np.array([np.random.rand(X.shape[1]) for i in range(Y.size)])
waights

array([[0.63521919],
       [0.55251768],
       [0.16237925],
       [0.38319936],
       [0.24789322],
       [0.0080916 ],
       [0.44416706],
       [0.86740047],
       [0.24620763],
       [0.98955708],
       [0.5186222 ],
       [0.13412831],
       [0.75526092]])

In [65]:
updatedWaights = train(X, Y, waights)

IndexError: index 1 is out of bounds for axis 0 with size 1